# Conda env config
# ----------------

# To create:
#   $ conda env create -f environment.yml

# To activate:
#   $ conda activate up42-challenge-environment

# To update:
#   $ conda env update -f environment.yml

# To remove:
#   $ conda remove --name up42-challenge-environment --all -y

---

name: up42-challenge-environment

channels:
    - defaults

dependencies:

    - python=3.7
    - pip=20.2.2
    - libspatialindex
    - matplotlib=3.0.3

    - pip:

          - numpy>=1.19.0
          - pandas==1.1.3

          - sentinelhub==3.2.1
          - rasterio==1.1.8
          - geopandas==0.8.1


