# Conda env config
# ----------------

# To create:
#   $ conda env create -f environment.yml

# To activate:
#   $ conda activate up42-challenge-environment

# To update:
#   $ conda env update -f environment.yml

# To remove:
#   $ conda remove --name up42-challenge-environment --all -y

---

name: up42-challenge-environment

channels:
    - defaults
    - conda-forge

dependencies:

    - python=3.8
    - pip=20.2.4
    - libspatialindex

    - pip:

          - loguru==0.5.3

          - numpy>=1.19.0
          - pandas==1.1.3

          - scikit-learn==0.24.1
          - keras==2.4.3
          - tensorflow==2.4.1
          - tensorflow-addons==0.12.1
          - tensorflow-datasets==4.3.0

          - matplotlib==3.4.0
          - seaborn==0.11.1
          - pillow==8.2.0



